Metrics/LineLength:
  Max: 130
  AllowHeredoc: true
  AllowURI: true
  IgnoreCopDirectives: true
  Exclude:
    - "spec/**/*"

# This cop checks the line count inside blocks.
# All RSpec code is in the same block for each file.
# Enabling this for spec/ would require cutting up the spec files in several parts.

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: "double_quotes"
