#!/usr/bin/env ruby
# frozen_string_literal: true

lib = File.expand_path("../lib", __dir__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

require "byebug" if ENV["DEBUG"]
require "maestry"
require "optionparser"

options = Struct.new(:config_file).new

OptionParser.new do |opts|
  opts.banner = [
    "Usage: maestry [-c config-file.yml]",
    "Default config files considered: #{Maestry::Configuration::DEFAULT_FILES.join(', ')}\n\n"
  ].join("\n")

  opts.on("-c", "--config-file [file]", "Maestry config file to use") do |file|
    options.config_file = file
  end

  opts.on("--clear-cached", "Remove all Maestry generated docker images (#{Maestry::Images::CACHED_IMAGES_NAME}:*)") do
    Maestry::Images.clear_cached
    exit 0
  end

  opts.on("-h", "--help", "Prints this help") do
    puts opts
    exit 0
  end
end.parse!

begin
  config = Maestry::Configuration.new(options.config_file)
  Maestry::Coordinator.run(config)
rescue StandardError => e
  Maestry::LOG.error(e.message)
  Maestry::LOG.error(e.backtrace.join("\n")) if ENV["DEBUG"]
  exit 1
end
