#!/usr/bin/env ruby
# frozen_string_literal: true

lib = File.expand_path("../lib", __dir__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

require "byebug" if ENV["DEBUG"]
require "maestry"
require "optionparser"

options = Struct.new(:config_file).new

OptionParser.new do |opts|
  opts.banner = [
    "Usage: maestry [-c config-file.yml]",
    "Default config files considered: #{Maestry::Configuration::DEFAULT_FILES.join(', ')}"
  ].join("\n")

  opts.on("-c", "--config-file [file]", "Maestry config file to use") do |file|
    options.config_file = file
  end

  opts.on("-h", "--help", "Prints this help") do
    puts opts
    exit
  end
end.parse!

begin
  coordinator = Maestry::Coordinator.new(config_file: options.config_file)
  coordinator.run
rescue StandardError => e
  puts
  puts e.message
  exit 1
end
